In [130]:
import requests
import json
import pandas as pd

In [131]:
response_API = requests.get('https://api.propertydata.co.uk/sold-prices?key=DCR205CWVJ&postcode=SE182QX&bedrooms=3')
#print(response_API.status_code)

In [132]:
data = response_API.json()
raw_data = data.get("data").get("raw_data")
# data



df = pd.json_normalize(raw_data)

In [133]:
df
# to lat and lng to addresses use google geoconding API

,date,address,price,lat,lng,bedrooms,type,tenure,class,distance
0,2022-04-01,"4, Macoma Terrace, SE18 2QN",585000,51.479990,0.082226,3,terraced_house,freehold,old_stock,0.08
1,2021-09-03,"15, Ennis Road, SE18 2QR",525000,51.478884,0.079037,3,terraced_house,freehold,old_stock,0.08
2,2022-04-29,"36, Admaston Road, SE18 2TX",384000,51.480137,0.077712,3,terraced_house,freehold,old_stock,0.15
3,2022-02-11,"118, Admaston Road, SE18 2TF",615000,51.477743,0.077181,3,terraced_house,freehold,old_stock,0.18
4,2022-09-23,"25, Plum Lane, SE18 3AF",565000,51.480442,0.077117,3,semi-detached_house,freehold,old_stock,0.18
5,2022-06-27,"120, Admaston Road, SE18 2TF",570000,51.477743,0.077181,3,terraced_house,freehold,old_stock,0.18
6,2022-06-13,"15, Pendrell Street, SE18 2PH",330000,51.478417,0.085250,3,flat,leasehold,old_stock,0.20
7,2022-04-21,"33, Vambery Road, SE18 3HA",590000,51.480134,0.075886,3,terraced_house,freehold,old_stock,0.22
8,2022-01-21,"5, Blendon Terrace, SE18 7RS",425000,51.481532,0.077097,3,terraced_house,freehold,old_stock,0.22
9,2021-08-27,"80, Garland Road, SE18 2PN",363000,51.477156,0.084648,3,terraced_house,freehold,old_stock,0.22
10,2021-12-07,"93, Garland Road, SE18 2PL",415000,51.477197,0.085175,3,terraced_house,freehold,old_stock,0.24
11,2022-07-29,"18, Vambery Road, SE18 3HA",575000,51.480213,0.075320,3,terraced_house,freehold,old_stock,0.24
12,2021-09-10,"14, Nyanza Street, SE18 2RY",387000,51.478099,0.086255,3,terraced_house,freehold,old_stock,0.25
13,2021-10-29,"2, Blendon Terrace, SE18 7RR",630000,51.482488,0.077561,3,terraced_house,freehold,old_stock,0.26
14,2021-09-17,"6, Blendon Terrace, SE18 7RR",630000,51.482590,0.077562,3,terraced_house,freehold,old_stock,0.27
15,2021-11-12,"36, Vernham Road, SE18 3EZ",650000,51.479858,0.074280,3,terraced_house,freehold,old_stock,0.28
16,2021-11-29,"159, Garland Road, SE18 2PP",425000,51.475105,0.083541,3,terraced_house,freehold,old_stock,0.31
17,2022-05-13,"16, Warland Road, SE18 2EU",485000,51.475123,0.084901,3,semi-detached_house,freehold,old_stock,0.33
18,2022-08-05,"70, Nithdale Road, SE18 3PD",530000,51.477746,0.073466,3,terraced_house,freehold,old_stock,0.33
19,2021-06-30,"25, Warland Road, SE18 2EX",435000,51.475268,0.085536,3,semi-detached_house,freehold,old_stock,0.34

In [126]:

# Code used to generate address based on just the x and y co ordinates

# from geopy.geocoders import Nominatim
# arrayAddress = []
# for i in range(len(df)) :
#     x = df.loc[i]['lat']
#     y = df.loc[i]['lng']
#     coOrdinates = str(x+","+y)
#     geolocator = Nominatim(user_agent="propertyAddress")
#     location = geolocator.reverse(coOrdinates)
#     propertyAddress = location.address
#     arrayAddress.append(propertyAddress)


# arrayAddress

['Tuam Road, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2QX, United Kingdom',
 'Tuam Road, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2QX, United Kingdom',
 'Chelsworth Drive, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2RA, United Kingdom',
 'Macoma Road, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2QP, United Kingdom',
 'Cheriton Drive, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2QY, United Kingdom',
 'Wernbrook Street, Glyndon, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 7RX, United Kingdom',
 'Kirk Lane, Glyndon, Shooters Hill, Royal Borough of Greenwich, London, Greater London, England, SE18 3AD, United Kingdom',
 'Kirk Lane, Glyndon, Shooters Hill, Royal Borough of Greenwich, London, Greater London, England, SE18 3AD, United Kingdom',
 'Chelsworth Drive, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2RA, United Kingdom',
 'Hatton Close, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2PY, United Kingdom',
 'Albatross Street, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2SA, United Kingdom',
 'Nithdale Road, Shooters Hill, Royal Borough of Greenwich, London, Greater London, England, SE18 3PD, United Kingdom',
 'Warland Road, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2EX, United Kingdom',
 'Pegwell Street, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2SE, United Kingdom',
 'Vicarage Place, Glyndon, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 7ST, United Kingdom',
 'Waverley Crescent, Glyndon, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 7QT, United Kingdom',
 'Bramblebury Road, Glyndon, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 7TF, United Kingdom',
 'Warland Road, Plumstead, Royal Borough of Greenwich, London, Greater London, England, SE18 2EX, United Kingdom',
 'Wrottesley Road, Glyndon, Shooters Hill, Royal Borough of Greenwich, London, Greater London, England, SE18 3RB, United Kingdom',
 'Nithdale Road, Shooters Hill, Royal Borough of Greenwich, London, Greater London, England, SE18 3PD, United Kingdom']